version: "3"
services: 
   grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
   alert:
    image: prom/alertmanager
    ports:
    - "9093:9093"
   prometheus:
    image: prom/prometheus
    volumes:
    - "./rules:/rules"
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090" 
   roach1:
    image: cockroachdb/cockroach:v19.1.5
    hostname: roach1
    command:  start --insecure
    volumes: 
    - "./data1:/cockroach/cockroach-data"
    ports:
    - "26257:26257"
    - "8081:8080"
   roach2:
    image: cockroachdb/cockroach:v19.1.5
    hostname: roach2
    command: start --insecure --join=roach1
    volumes: 
    - "./data2:/cockroach/cockroach-data"
    ports:
    - "26258:26257"
    - "8082:8080"
   roach3:
    image: cockroachdb/cockroach:v19.1.5
    hostname: roach3
    command: start --insecure --join=roach1
    volumes: 
    - "./data3:/cockroach/cockroach-data"
    ports:
    - "26259:26257"
    - "8083:8080"
   