# Prometheus configuration for cockroach clusters.
# Requires prometheus 2.X
#
# Run with:
# $ prometheus -config.file=prometheus.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
- "/rules/alerts.rules.yml"
- "/rules/aggregation.rules.yml"

# Alert manager running on the same host:
alerting:
  alertmanagers:
  - path_prefix: "/alertmanager/"
    static_configs:
    - targets:
      - alert:9093

scrape_configs:
  - job_name: 'cockroachdb'
    metrics_path: '/_status/vars'
    # Insecure mode:
    scheme: 'http'
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ['roach1:8080','roach2:8080','roach3:8080']
      labels:
        cluster: 'my-cockroachdb-cluster'
